### ISSUE TITLE
Inertia Requires Rails Gem Instead of Select Deps

### ISSUE THREAD

**Issue by BenMorganMY** [inertiajs/inertia-rails#104]
I noticed inside of the inertia gem that it is just rails marked as the dependency. Would it be possible to reduce it to just railties or the action/active deps that required by inertia_rails?

**Comment by Austio** [comment]
Makes sense to me to limit to what is required here, could you make a PR?

**Comment by BenMorganMY** [comment]
Yep, this is the PR: https://github.com/inertiajs/inertia-rails/pull/106

**Comment by BrandonShar** [comment]
Merged and tagged!
