### ISSUE TITLE
How to not call createInertiaApp on non Inertia pages?

### ISSUE THREAD

**Issue by AlvesJorge** [inertiajs/inertia-rails#123]
This is a discussion / help request, more than an issue.

My Rails app has both `*.html.erb` pages and `*.vue` pages.

It renders the `*.vue` pages when I explicitely call `render inertia` on the controller, and renders `*.html.erb` when the render is implicit.

My problem is the `application.js` runs on every page load, and Ideally, it wouldn't run on the `*.html.erb` pages. Any idea on how to detect this? 

On `*.html.erb` load I get:
`TypeError: Cannot read properties of null (reading 'dataset')` 
Because I am of course not passing any inertia data here. 

Perhaps `createInertiaApp` can be wrapped with a `if(datasetPresent){}` but I don't know what attribute to check there :)

**Comment by skryukov** [comment]
I believe you can search for a root element in the DOM. By default, it's `div#app` (see https://inertia-rails.netlify.app/guide/client-side-setup.html#defining-a-root-element). However, I would also consider using separate root layouts and/or JS entrypoints if that's applicable to your situation. (docs on root templates https://inertia-rails.netlify.app/guide/server-side-setup.html#root-template)
