### ISSUE TITLE
[Potential Issue] [No Reproduction] Every successful route, also sends a "cancelled" request for each past successful request.

### ISSUE THREAD

**Issue by AlvesJorge** [inertiajs/inertia-rails#125]
Writing in hope that perhaps someone is seeing this issue and might know what's going on.
Can't reproduce this even on my own code, it just happens sometimes. 
I have a paginated Rails + Inertia + Vue app with a _next page button_ where users click "Next" and `router.visit()` takes them to the next URL. 
Usually requests in the network tab look like this:
```
page1 | 200 | 1kb | 200ms

page2 | 200 | 1.2kb | 240ms

page3 | 200 | 1kb | 200ms

page4 | 200 | 1.4kb | 260ms

page5 | 200 | 1kb | 200ms
```
Other times, and no idea why:
```
page1 | 200 | 1kb | 200ms

page2 | cancelled | 0kb | 0ms
page2 | 200 | 1.2kb | 240ms

page3 | cancelled | 0kb | 0ms
page3 | cancelled | 0kb | 0ms
page3 | 200 | 1kb | 200ms

page4 | cancelled | 0kb | 0ms
page4 | cancelled | 0kb | 0ms
page4 | cancelled | 0kb | 0ms
page4 | 200 | 1.4kb | 260ms

page5 | cancelled | 0kb | 0ms
page5 | cancelled | 0kb | 0ms
page5 | cancelled | 0kb | 0ms
page5 | cancelled | 0kb | 0ms
page5 | 200 | 1kb | 200ms

```
It is usually solved by manually refreshing the page, and I don't think there's much user impact.

**Comment by skryukov** [comment]
Have you tried adding [router listeners](https://inertia-rails.netlify.app/guide/events.html#registering-listeners)?

Something like this might provide more info about the source of those calls:

```js
router.on('start', (event) => console.log('Navigation started', event))
router.on('finish', (event) => console.log('Navigation finished', event))
router.on('cancel', (event) => console.log('Navigation cancelled', event))
```

**Comment by AlvesJorge** [comment]
Thanks @skryukov, I added these as debug logs in case I catch the error happening again

**Comment by AlvesJorge** [comment]
This was unrelated to inertiajs.

I simply wasn't cleaning up my keydown event listeners, and when I would navigate to a new page with inertia router using a keydown event, the old event listener would still be there, and would try to send the inertia router request.
