### ISSUE TITLE
Could you elaborate on "Instance props are only included if they are defined after the before filter is set from use_inertia_instance_props."

### ISSUE THREAD

**Issue by AlvesJorge** [inertiajs/inertia-rails#126]
This is on the readme and I don't quite understand it.
What does "after the before filter is set" mean? What is the `before filter`?

Thank you!

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @AlvesJorge, I think the nomenclature is outdated. The right one is before_action. before filter was an old rails hook, extinct in rails 5.1: https://stackoverflow.com/questions/16519828/rails-4-before-filter-vs-before-action

This phrase means that you have to call instance props after the `use_inertia_instance_props` method call, like that:
https://github.com/inertiajs/inertia-rails/blob/6e0fc5a92cafd5e821e6918168260d0e2fbce539/spec/dummy/app/controllers/inertia_rails_mimic_controller.rb#L1-L10

The `use_inertia_instance_props` is basically a `before_action` and skips the props defined before: https://github.com/inertiajs/inertia-rails/blob/6e0fc5a92cafd5e821e6918168260d0e2fbce539/lib/inertia_rails/controller.rb#L38-L43

**Comment by skryukov** [comment]
I rephrased that for Inertia Rails docs as:
> Instance props are only included if they are defined after the `use_inertia_instance_props` call, hence the order of `before_action` callbacks is crucial.

**Comment by AlvesJorge** [comment]
Thanks Pedro for the exaplanation and thanks Svyatoslav for the update on the Docs!
