### ISSUE TITLE
Link to example app

### ISSUE THREAD

**Issue by ledermann** [inertiajs/inertia-rails#14]
I've build an example app on how to use Inertia.js with Rails using this gem. Maybe it's worth to add a link to the README:

https://github.com/ledermann/workcation/

**Comment by BilalBudhani** [comment]
Just had a look at @ledermann's workcation sample rails app and I must say it is quite well done. Thank you for your effort @ledermann.

**Comment by BrandonShar** [comment]
Hey @ledermann, thanks for setting this up! @reinink has been moving any doc-based resources to a separate docs site (https://github.com/inertiajs/inertiajs.com). Maybe he would be interested in linking to it from there?

**Comment by ledermann** [comment]
In the meantime I build the PingCRM clone which is linked from the official Inertia.js website:
https://inertiajs.com/demo-application

It demonstrates much more features than the Workcation example, so I close this issue.
