### ISSUE TITLE
TypeScript + Svelte doesn't work; generator keeps reverting package to incompatible version

### ISSUE THREAD

**Issue by unikitty37** [inertiajs/inertia-rails#173]
I see that I need to use version 2 of `@inertiajs/svelte` to get TypeScript support:

```
Would you like to use TypeScript? (y/n) y
Adding TypeScript support
What framework do you want to use with Inertia? [react, vue, svelte4, svelte] (react) svelte
WARNING: @inertiajs/svelte < 1.3.0 does not support TypeScript (resolved version: 1.2.0).
Skipping TypeScript support for @inertiajs/svelte
```

but when I change the version in `package.json` to `^2.0.0-beta.3` and run `pnpm i`, then rerun the generator, I get the message above again. The version in `package.json` has been reverted to `^1.2.0`, which should not happen — and it happens _even if I remove write permission for `package.json`!_ (This is running in a devcontainer, but the uid and gid are 1000, so it shouldn't be down to Docker's "default to root everywhere" behaviour :)

I have a limited amount of time available to evaluate Inertia, but it does have to be with Svelte 5 and TypeScript. Is there a way to get this working yet, or at least to get it to stop rewriting my `package.json`?

(I did try the v2 branch, but it installs v3.4.0, not v3.5.0, and doesn't even _have_ the `inertia:install` generator 😕)

**Comment by unikitty37** [comment]
Thanks — I went back from the v2 branch to `gem "inertia_rails", "~> 3.5" in the Gemfile and re-ran `bundle install`.

It doesn't seem to make any difference, unfortunately:

```
vscode ➜ /workspaces/inertia-test (main) $ pnpm i                                        
Packages: +4
++++
Progress: resolved 121, reused 82, downloaded 0, added 0, done

dependencies:
- @inertiajs/svelte 1.2.0
+ @inertiajs/svelte 2.0.0-beta.3

Done in 1s
vscode ➜ /workspaces/inertia-test (main) $ rails g inertia:install --version=2.0.0-beta.3
Installing Inertia's Rails adapter
Would you like to use TypeScript? (y/n) y
Adding TypeScript support
What framework do you want to use with Inertia? [react, vue, svelte4, svelte] (react) svelte
WARNING: @inertiajs/svelte < 1.3.0 does not support TypeScript (resolved version: 1.2.0).
Skipping TypeScript support for @inertiajs/svelte
Would you like to install Tailwind CSS? (y/n) n
Adding Inertia's Rails adapter initializer
   identical  config/initializers/inertia_rails.rb
Installing Inertia npm packages
         run  pnpm add svelte@5 @sveltejs/vite-plugin-svelte@4 --silent from "."
         run  pnpm add @inertiajs/svelte@latest --silent from "."
Copying inertia.js entrypoint
   identical  app/javascript/entrypoints/inertia.js
Adding inertia.js script tag to the application layout
   unchanged  app/views/layouts/application.html.erb
Copying example Inertia controller
   identical  app/controllers/inertia_example_controller.rb
Adding a route for the example Inertia controller
       route  get 'inertia-example', to: 'inertia_example#index'
Copying page assets
   identical  svelte.config.js
   identical  app/javascript/assets/svelte.svg
   identical  app/javascript/assets/inertia.svg
   identical  app/javascript/assets/vite_ruby.svg
   identical  app/javascript/pages/InertiaExample.svelte
Copying bin/dev
   identical  bin/dev
Inertia's Rails adapter successfully installed
vscode ➜ /workspaces/inertia-test (main) $ 
```

…and the version in `package.json` is reverted once again.

Running `bin/rails g inertia:install --help` doesn't show a `--version` flag, incidentally (and passing something unsupported like `--sausage` doesn't produce an error message, so it's possible that `--version` isn't supported in this version as well :)

**Comment by skryukov** [comment]
Oh, sorry it's `--inertia-version` 😅 

Regarding v2 vs master — yes, great catch! we definitely have this problem and need to rebase v2! cc @bknoles

**Comment by unikitty37** [comment]
Thanks — that's fixed it 👍
