### ISSUE TITLE
having `gem inertia_rails` in Gemfile disables errors messages

### ISSUE THREAD

**Issue by buhrmi** [inertiajs/inertia-rails#29]
There's something strange happening with the inertia_rails gem: Whenever it is included in the Gemfile, Rails stops showing full errors messages in development mode and only servers the 500.html file whenever there is an error. It doesn't matter if the error is Inertia-related or not...

**Comment by buhrmi** [comment]
I've worked around it by adding `better_errors` to my Gemfile.

**Comment by ledermann** [comment]
Maybe this has something to do with #21 where we monkey-patched Rails exception handling.

But: I can't reproduce your issue. The [PingCRM demo application](https://github.com/ledermann/pingcrm) doesn't use the `better_errors` gem and correctly shows full error messages in development mode. A plain new Rails 6 application with added `inertia_rails` gem works fine, too.

Do you have any more details about this issue? Which Rails version do you use?

**Comment by buhrmi** [comment]
It's an old app that I inherited. Rails 4.2. I've upgraded it to 5.2 and it seems to work fine now.
