### ISSUE TITLE
inertia-rails gem not found

### ISSUE THREAD

**Issue by magiknono** [inertiajs/inertia-rails#3]
hello,
I want to test inertia but i can't install the inertia-rails gem as specified in doc.

i tested 3 ways:
- commandline: gem install inertia-rails 
- via gemfile: gem 'inertia-rails', git: 'https://github.com/inertiajs/inertia-rails.git' (& bundle install)

And not found on rubygems.org when i search for inertia-rails

screen capture:
https://pbs.twimg.com/media/EF4-xSLXkAERhJu?format=png&name=900x900
https://pbs.twimg.com/media/EF4-xSLXYAECUrg?format=png&name=900x900

Can you help me?

**Comment by magiknono** [comment]
OK, solved with https://github.com/inertiajs/inertia-rails/tree/readme-updates

**Comment by rbngzlv** [comment]
@reinink @BrandonShar related to this issue I was going to send a PR to update the documentation on the website, because the gem is not published yet and the actual instructions are wrong. But maybe you have planned to publish the gem soon?

If anyone comes here the correct line is:

```ruby
gem 'inertia', git: 'https://github.com/inertiajs/inertia-rails/'
```

**Comment by BrandonShar** [comment]
Thanks for calling this out! @bknoles we have a few installs now, do you feel comfortable tagging / publishing a first version of the gem?

**Comment by reinink** [comment]
Gents, let me know if you need help publishing the gem. I say get it out there, and we can always improve on it if there are bugs. 👍 

Also, if you're able to review the new website and PR improvements to the Rails documentation, that would be greatly appreciated!

**Comment by bknoles** [comment]
yea, let's try to release it this week @BrandonShar

**Comment by bknoles** [comment]
closing in favor of #6
