### ISSUE TITLE
Document inertia_location feature

### ISSUE THREAD

**Issue by BrandonShar** [inertiajs/inertia-rails#49]
Per #48

**Comment by reinink** [comment]
You'll want to add this to the redirects page, [here](https://inertiajs.com/redirects#external-redirects). I've already created a placeholder to put this code sample in. The file to edit is [this one](https://github.com/inertiajs/inertiajs.com/blob/master/pages/redirects.mdx). ❤️ 

![image](https://user-images.githubusercontent.com/882133/95411648-06430f80-08f5-11eb-886a-be68397f7527.png)
