### ISSUE TITLE
Ensure turbonlinks: false on redirects allows Inertia and Turbolinks to coexist

### ISSUE THREAD

**Issue by bknoles** [inertiajs/inertia-rails#5]
In #2, @savroff reported that 

```ruby
redirect_to my_path, turbolinks: false
```

allows Turbolinks to coexist with Inertia... would love to add that to the README, but i want us to confirm it in a test app first.

**Comment by jamgar** [comment]
@bknoles thank you for contribution. I have tested using Turbolinks with Inertia before I found this issue. It is a play app so I know it is ugly 😆 . Below is the link. You will see the use of `turbolinks: false` in the notes_controller.rb and sessions_controller.rb. I just wanted to share my two cents. https://github.com/jamgar/test-inertia/blob/master

**Comment by BrandonShar** [comment]
Thanks @jamgar ! I'm going to close this issue because I think the reason for opening it is stale (the readme is now just a link to the main docs) and our official installer recommends just not using turbolinks. Glad to have this for reference though!

**Comment by narze** [comment]
I stumbled upon this and tried make Inertia & Turbo co-exist, so that I don't have to add `{ turbo: false }` everywhere in my app

This is the code, I'm using Svelte 5 but other frontend framework should work the same

```javascript
import { createInertiaApp } from "@inertiajs/svelte"
import { mount, unmount } from "svelte"

let app

function loadInertiaApp() {
  // Prevent inertia app to run on non-inertia pages
  if (
    typeof window === "undefined" ||
    document.getElementById("app") === null
  ) {
    return
  }

  createInertiaApp({
    resolve: name => {
      const pages = import.meta.glob("../pages/**/*.svelte", { eager: true })
      const page = pages[`../pages/${name}.svelte`]

      return page
    },

    setup({ el, App, props }) {
      if (app) unmount(app)

      app = mount(App, { target: el, props })
    },
  })
}

if (Turbo?.session?.enabled) {
  document.addEventListener("turbo:load", loadInertiaApp)
} else {
  document.addEventListener("DOMContentLoaded", loadInertiaApp)
}
```
