### ISSUE TITLE
Add lazy props feature

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia-rails#51]
So I just added "lazy props" to the Laravel adapter: https://github.com/inertiajs/inertia-laravel/pull/175. It would be awesome to bring this same behaviour to the Rails adapter.

Lazy props are simply data that's *not* included on the initial visit to a page. It's only ever included when doing partial reloads, using the `only` key.

It was actually very easy to implement in the Laravel adapter. I created a new `LazyProps` class, that acts a "marker" for these props. Then, on regular (non partial reload) visits, I simply filter these props out.

**Comment by bknoles** [comment]
This is an interesting feature! I implemented it in #52 

The code design follows the Laravel adapter quite closely. The API is here:
https://github.com/inertiajs/inertia-rails/pull/52/files#diff-c16edceefc6f6d252909536c933e5e559583bc0b0546f5cbd2ec998d798bd133R24

I'll merge this in once @BrandonShar takes a look and offers feedback!
