### ISSUE TITLE
Error when trying to run the specs

### ISSUE THREAD

**Issue by christoomey** [inertiajs/inertia-rails#55]
Hey inertia-rails team, first of all, thanks for the great work on this project 👋!

I unfortunately was unable to get the tests running locally as I'm hitting the following error:

<details>
  <summary><strong>Error output when running `bundle exec rake`</strong></summary>

```
An error occurred while loading rails_helper.
Failure/Error: 'Cache-Control' => "public, max-age=#{1.hour.to_i}"

NoMethodError:
  undefined method `hour' for 1:Integer
# ./spec/dummy/config/environments/test.rb:19:in `block in <top (required)>'
# ./spec/dummy/config/environments/test.rb:6:in `<top (required)>'
# ./spec/dummy/config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
No examples found.
No examples found.
```
</details>

I'm guessing there's some setup step needed in the spec/dummy app or similar, but not sure what it is. I'd be more than happy to document or add to `bin/setup` if you point me in the right direction.

**Comment by ledermann** [comment]
It seems this is caused by Rails 6.1, which requires this line to be added on top of `spec/dummy/config/environments/test.rb`:

```ruby
require 'active_support/core_ext/integer/time'
```

See http://railsdiff.org/6.0.3.4/6.1.0

**Comment by BrandonShar** [comment]
Thanks @christoomey and @ledermann! Great issue info and solution.
