### ISSUE TITLE
Misleading "Inertia test helpers aren't set up!" warning

### ISSUE THREAD

**Issue by christoomey** [inertiajs/inertia-rails#61]
I've been using the spec helper and I've run into an issue where I'm seeing "Inertia test helpers aren't set up!", despite the fact that they are indeed set up. In my case I ran into this when a `before_action` that I was not expecting to run did end up running, and thus I never got to the `render(inertia ...` call.

This seems to be due to the fact that [the stubbing of `render` method](https://github.com/inertiajs/inertia-rails/blob/5c71d77dec869e130356ec4d259c94f4adbb30b2/lib/inertia_rails/rspec.rb#L63-L65) is done lazily when the `render(inertia ...` is actually called.

Presuming these spec helpers are intended for use in applications and not just for the library itself (which I really hope is the intention as they're great!), I think it would be great to look into fixing this as it can lead to a confusing experience. I'd be happy to poke around and see if I could resolve this and open a PR if I could, but wanted to start with an issue to see if there are any existing thoughts or constraints I'm unaware of.

Thanks again for the great library!

**Comment by bknoles** [comment]
hey @christoomey thanks for calling this out! it has tripped me up in the past as well. @BrandonShar and I talked about it sometime last year and then promptly forgot about it 😂 

I think #62 should take care of it. take a look and let me know if you have any comments on the PR!
