### ISSUE TITLE
With SSR enabled, X-Inertia requests doesn't work

### ISSUE THREAD

**Issue by 99monkey** [inertiajs/inertia-rails#76]
SSR is a great tool for SEO oriented projects.
So we expect to get html for common requests, but it doesn't make sense to retrieve html on real user after loading first page (X-Inertia requests)

I opened PR  https://github.com/inertiajs/inertia-rails/pull/75

Another point is to have regress-strategy if node server fails or doesn't run (during restart time). 

Really appreciate inertia project. So please leave me a comment

**Comment by BrandonShar** [comment]
Thanks @99monkey ! Just tagged a new release (`1.12.1`) that includes your fix from #75
