### ISSUE TITLE
Cannot change inertia shared data

### ISSUE THREAD

**Issue by bknoles** [inertiajs/inertia-rails#8]
In my local test app, if i change (or remove) shared data, the old data is still sent to the component.

i.e. setting in the controller

```
inertia_share test: 'thing'
```

making a request, then changing the controller to:

```
inertia_share test: 'another thing'
```

sends `{ "test": "thing" }` to the controller.

I believe we maybe aren't merging shared data correctly or something like that. 

Note:This also could be due to the fact I'm running the app through Docker for Mac... sometimes Docker will cache classes if you don't have the right setting in your `development.rb`. I don't think that's the case here, but noting it in case someone else picks this up.
```

**Comment by rbngzlv** [comment]
@bknoles I have encountered this too but I have not investigated yet, I also use Docker, but on Linux, and I want to think that this will not be the reason.

**Comment by bknoles** [comment]
haha yea, i didn't get to dig into it yet, but i'm fairly confident it's from the gem and not Docker this time.

**Comment by BrandonShar** [comment]
Let's make sure we add a regression test whenever we fix this.
