### ISSUE TITLE
Setting up React hot module replacement with Webpack?

### ISSUE THREAD

**Issue by andreivolt** [inertiajs/inertia-rails#89]
I haven't found anything about setting up hot module reload in this context. In an SPA setup Webpack would handle it all through the dev server, I'm wondering if such a setup is possible here. Would appreciate any pointers!

**Comment by BrandonShar** [comment]
Hey @andreivolt, your HMR setup should be the same as usual since it's controlled through something like Vite or Webpack, not Inertia.

**Comment by andreivolt** [comment]
Thank you, I just set it up and it's working perfectly, I was thinking there would be something extra because the html isn't handled by the bundler but that was misguided.

And thank you for Inertia!
