### ISSUE TITLE
event handlers are not bounded, with hydrateRoot

### ISSUE THREAD

**Issue by awkward-minion** [inertiajs/inertia-rails#91]
### Versions:

- `inertia_rails` version: 3.0

### Describe the problem:

The javascript event listeners are not attached to the HTML even after `hydrating`. 
Example: let's assume there is an event handler registered for an input field named `name`. Whenever the user changes the value in the text field, the event listeners should fire.

### Steps to reproduce:

Reproduction repository: https://github.com/awkward-minion/inertiajs-react-form-handlers.git

The browser renders this problem without any issues. 
But the event handlers like `handleSubmit` and `handleChange` are not registered after the **hydration**.

## Observations

1. SSR is properly generating HTML markup along with layout
2. Client-side `hydrateRoot` was not displaying any warnings, considering it as good. The javascript `bundle` is being loaded in the browser. (the event handlers)
3. **Problem** - the event handlers are not bonded 

Raised [issue](https://github.com/inertiajs/inertia/issues/1314) in `inertia.js` rails repository

**Comment by BrandonShar** [comment]
Hey @awkward-minion I saw you discussing this on discord and I believe the correct place for this issue is in the `inertia.js` repo (where you already opened one), so I'm going to close this issue. Feel free to re-open if you think I misunderstood!
